Unifik\DoctrineBehaviorsBundle\Entity\Tagging:
  type: entity
  uniqueConstraints:
    tagging_unique_index:
      columns: [tag_id, resourceType, resourceId]
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    resourceType:
      type: string
      nullable: true
    resourceId:
      type: integer
      nullable: false
  manyToOne:
    tag:
      inversedBy: taggings
      targetEntity: Unifik\DoctrineBehaviorsBundle\Entity\Tag
      joinColumn:
        name: tag_id
        referencedColumnName: id
        onDelete: cascade
